data_dir = "/var/lib/vector"

[sources.file_k8slog]
  type         = "file"
  include      = ["/var/log/*.log"]
  #ignore_older = 86400 # 1 day

[transforms.jsonparse_k8slog]
  type = "json_parser"
  inputs = ["file_k8slog"]
  field = "message"
  drop_invalid = true

[transforms.regexparse_k8slog_nginx]
  type = "regex_parser"
  inputs = ["jsonparse_k8slog"]
  field = "log"
  regex = "/^(?P<remote>[^ ]*) (?P<host>[^ ]*) (?P<user>[^ ]*) \[(?P<time>[^\]]*)\] "(?P<method>\S+)(?: +(?P<path>[^ ]*) +\S*)?" (?P<code>[^ ]*) (?P<size>[^ ]*)(?: "(?P<referer>[^\"]*)" "(?P<agent>[^\"]*)" "(?P<forwarder>[^\"]*)")?/"


[transforms.remove_fields_k8slog]
  type = "remove_fields"
  inputs = ["regexparse_k8slog_nginx"]
  fields = ["file", "host", "source_type"]


[sinks.aws_s3_k8slog]
  inputs       = ["remove_fields_k8slog"]
  type         = "aws_s3"
  region       = "ap-northeast-1"
  bucket       = "k8s_log"
  key_prefix   = "%Y/%m/%d/%H/"
  encoding     = "ndjson"
  compression  = "gzip"
  [sinks.s3_transfer.batch]
    max_size   = 1000000 # 1mb uncompresse
    timeout_secs = 30
