---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID: Y2hpZ2F1eW9vbwo= #base64
  AWS_SECRET_ACCESS_KEY: Y2hpZ2F1eW9vbwo= #base64


---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector-s3
spec:
  selector:
    matchLabels:
      app: vector-s3
  template:
    metadata:
      labels:
        app: vector-s3
    spec:
      containers:
      - env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: aws-secrets
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: aws-secrets
        image: vector-s3-alpine:latest
        imagePullPolicy: Never
        name: vector-s3-container
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/vector/
          name: data-dir-vector
      volumes:
      - hostPath:
          path: /var/log
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
        name: varlibdockercontainers
      - hostPath:
          path: /var/lib/vector/
        name: data-dir-vector

